stimulusreflex/cable_ready

- javascript/cable_ready.js
Adds support for permanent nodes, i.e. nodes that will not be replaced when the DOM is updated.
I read through [this issue for stimulus_reflex](https://github.com/hopsoft/stimulus_reflex/pull/43#issuecomment-536801378), and decided to try to create a solution for this. Since I couldn't find a way to do this from the stimulus_reflex source code, I'm submitting this as a PR to cable_ready.
To mark a node as permanent, give it the `data-reflex-permanent`-attribute:
````html
<input name="email" data-reflex-permanent />
````
This is similar to [how Turbolinks supports similar behavior](https://github.com/turbolinks/turbolinks#persisting-elements-across-page-loads).
stimulus_reflex is an amazing project, and I was blown away by how easy it was to create highly interactive UIs without a complex …
> Add support for permanent nodes

- .gitbook.yml
- CODE_OF_CONDUCT.md
- README.md
- docs/README.md
- docs/SUMMARY.md
- docs/dom-operations/attribute-mutations.md
- docs/dom-operations/css-class-mutations.md
- docs/dom-operations/dataset-mutations.md
- docs/dom-operations/dom-events.md
- docs/dom-operations/element-mutations.md
- docs/setup.md
- docs/supported-dom-operations.md
- docs/usage.md
- docs/xpath-example.md
Reorganize the documentation into a `docs/` folder and add gitbook styling. Also updates the README and adds COC.
> Add Gitbook integration

- lib/cable_ready/channel.rb
Under high volume when using with stimulus_reflex, I was seeing sporadic errors like `undefined method << for nil`. Not sure what the cause was but this did stop the errors for me.
> fix sporadic error - undefined method << for nil, when adding operation

- docs/setup.md
- javascript/cable_ready.js
While it is desirable to emit console log messages when an invalid DOM selector is received in development, in production there should be an escape hatch to suppress messages if a valid reason exists to do so.
This PR introduces an optional 2nd parameter to the perform method, an object called options. Currently, this object has a single key  `processMissing` which defaults to true. If set to false, DOMOperations will not be called unless there is a valid element in scope.
I added a documentation hint and supplemented the original catch block with a distinction to alert developers to the missing DOM element. I spent a lot of time trying to figure out what was going wrong before realizing that the element was missing due to an unhelpful default error message.
> Add support to ignore missing DOM elements via options parameter

- README.md
- javascript/package.json
Bring changes to stimulus_reflex README and package.json over to cable_ready.
> update README and package.json

- docs/README.md
- docs/SUMMARY.md
- docs/usage/dom-operations/README.md
- docs/usage/dom-operations/style-mutations.md
- javascript/cable_ready.js
- lib/cable_ready/channel.rb
While this isn't something you should be doing every day, dynamically setting an element's in-line style values is a legitimate intention in edge case scenarios. I believe that it was omitted from the library by virtue of being overlooked.
While it is possible to use the setAttribute method to update an element's in-line style attribute as a string, setting it actually overwrites any previous values. In other words, you either have to track which styles are set, or you have to arbitrarily limit developers to setting one style at a time.
> add set_style method to library

- javascript/cable_ready.js
This PR improves the error message when the sector fails by printing out the selector. You can easily grab that and run it in the console for debugging. 
```
CableReady morph failed due to missing DOM element for selector: 'card_3'
```
I ran into this when I was generating a `dom_id` in Ruby, without the `#` but it took me a bit to realize why.
Figured this would be useful for other people debugging their cable ready broadcasts.
> Print out the selector for easier debugging perform errors

- docs/README.md
- docs/usage/dom-operations/README.md
- docs/usage/dom-operations/element-mutations.md
- javascript/cable_ready.js
- lib/cable_ready/channel.rb
A marriage of set_attribute and set_value...
While it is true that 90% of the time you want to use set_attribute or set_value, there are scenarios in which a developer might want to set a property on an element.
This implementation runs a simple check to verify that a given property name is present in the element's property dictionary before setting the value. It does **not** attempt to verify that the developer has passed a value that is compatible with the property's data type. If someone tries to set an invalid data type, it will be caught by CR's standard try/catch error handling.
> add set_property method to library

- docs/usage/dom-operations/element-mutations.md
Typo found in the outerHTML element mutation example 
:)
> Correct method 'outerHtml' to 'outer_html' in documentation

- docs/README.md
- docs/usage/dom-operations/style-mutations.md
- javascript/cable_ready.js
- lib/cable_ready/channel.rb
This adds a `setStyles` operation that allows for setting multiple style attributes at once on an element. This actually loops through and delegates each entry to the `setStyle` operation.
For example, we can set background and color at once:
```ruby
cable_ready["MyChannel"].set_styles(
selector: "string", # required - string containing a CSS selector or XPath expression
styles: {
background: "red",
color: "white"
}
)
```
Depending on browser compatibility targets / goals, we could shorten this by one line using `Object.entries` instead. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries
> Add setStyles

- lib/cable_ready/broadcaster.rb
When calling CableReady, it is common to see
`cable_ready['identifier'].morph({selector: "#" + ActionView::RecordIdentifier.dom_id(user)})`
This PR would add a `dom_id(resource)` method to `CableReady::Broadcaster` and allow the following:
`cable_ready['identifier'].morph({selector: dom_id(user)})`
What's not to love?
> add dom_id helper

- lib/cable_ready/broadcaster.rb
I goofed - dom_id takes an important second parameter, prefix:
https://apidock.com/rails/ActionView/RecordIdentifier/dom_id
This PR is like #50 but better. It maintains the function signature 1:1.
> Dom id signature fix

- docs/usage/dom-operations/css-class-mutations.md
- javascript/cable_ready.js
Add support to add and remove multiple CSS classes on _addCssClass_ and _removeCssClass_ methods following the [classList](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) documentation.
For example, you can set "btn btn-light" at once:
```ruby
cable_ready["MyChannel"].add_css_class(
selector: "string", # required - string containing a CSS selector or XPath expression
name:     ["btn", "btn-light"]  # [null]   - the CSS class to add
)
```
> Support for multiple CSS classes.

- lib/cable_ready/channel.rb
- lib/cable_ready/channels.rb
CableReady::Channels exposes a public `broadcast_to(resource)` method, which is used to broadcast to an ActionCable channel which makes use of the `stream_for` method. When using `broadcast_to`, we pass the channel constant instead of a String-based identifier.
```ruby
class DocumentChannel < ApplicationCable::Channel
def subscribed
stream_for Document.find(params[:document_id])
end
end
class Document< ApplicationRecord
include CableReady::Broadcaster
after_save do
cable_ready[DocumentChannel].morph({selector: "#document", html: self.content})
cable_ready.broadcast_to(self)
end
end
```
A resource must be passed to the broadcast_to method. ActionCable builds a subscription handle based on the name of the channel and a unique hash of the resource.
When using CableReady, it is possible to …
> broadcast_to method

- javascript/cable_ready.js
- lib/cable_ready/broadcaster.rb
- lib/cable_ready/channel.rb
- lib/cable_ready/channels.rb
I spent a lot of time looking at @n-rodriguez' #43 because I **hate** that he has to monkey patch the library in order to add additional operations. There's been a few moments where we've idly talked about supporting configuration details and also I have long been irritated by the implicit singleton pattern implied in the way we use CableReady::Channels. It turns out that Ruby has a workable singleton module that we can use to start refacting how CR works behind the scenes, allowing for customization.
This PR would allow @n-rodriguez to just create `config/initializers/cable_ready.rb`:
```ruby
CableReady::Channels.configure do |config|
config.add_operation :notify
end
```
Thanks to @foca, @n-rodriguez also has the option to define the implementation of their new custom operation:
```ruby …
```
> Customize operations via initializer

- docs/README.md
- docs/usage/dom-operations/README.md
- docs/usage/dom-operations/cookies.md
- lib/cable_ready/channels.rb
Thanks to @julianrubisch who caught that the list of possible operations omitted `text_content`.
This is why pre-releases are so important!
> text_content is missing from 4.3.0.pre0

- javascript/cable_ready.js
- lib/cable_ready/channels.rb
- consoleLog(message, level)
- notification(title, options)
Before you say, "hey, weren't you complaining about having to write docs?" know that at least I stopped short of creating wrappers around the entire `console` object.
This sends messages to the browser console. It defaults to `log` level but you can specify `warn` `error` `info` as well. No events are emitted.
This is the real power-move: this will allow you to deliver desktop native notifications. It asks the user if they Approve or Block in a native popup; if they don't answer, it will ask them again next time. If they approve, you now have a direct route to their brains.
Title is officially required, but I have defaulted it to an empty string.
Options is an object that contains parameters for your popup. The most obviously …
> Notifications

- lib/cable_ready/channel.rb
Small change to remove the Ruby 3.0 warning:
```
...cable_ready-4.3.0/lib/cable_ready/channel.rb:19: warning: Passing the keyword argument as the last hash parameter is deprecated
```
> Add braces to hash parameter to remove warning

- javascript/cable_ready.js
In certain situations it can be preferable to `await` until morphdom operations are completed asynchronously to free the main thread to do other work. 
One example would be to trigger events that bubble up the DOM without waiting for the morphs to finish.
> Provide an async perform method

- javascript/cable_ready.js
Okay, so this is the result of a lot of iteration trying to get `children_only: false` to work properly with `data-reflex-permanent`. If we just keep `template.content` when using `children_only: false`, you end up with a number of strange situations, dending on the HTML you're trying to morph. I believe this is due to the differences between fromNode and toNode. This change results in my test project successfully rendering with children_only set to true or false, always respecting the permanent attribute.
I'm not 100% confident about the ramifications of this change, but I'm testing it in my expo app and everything's working as expected for all examples. 
This is related to issue 2 on the discord.
> For reasons we don't currently understand, when you do a :selector morph, it ignores …
> only pass inner html if childrenOnly is false

- lib/cable_ready/channels.rb
This resolves the issue discussed in #64 where the @channels object may be modified out-of-sync in a multi-threaded environment, potentially resulting in premature broadcasting or loss of operations before broadcast.
> Add a shared mutex to avoid concurrency issues in Channels

- javascript/cable_ready.js
- lib/cable_ready/channels.rb
I honestly thought that CableReady already did this. After all, the code was already written! But we never actually explicitly make it available.
> set_focus operation

- javascript/cable_ready.js
I was able to get StimulusReflex and CableReady working in IE11.  In addition to a bunch of polyfills (documented [here](https://gist.github.com/existentialmutt/7f32f9d3217d41a2d8bcd4c61aa201ec), I needed to make a small change to cable_ready.js
Event constructor is not supported in IE11 and CustomEvent.detail is a readonly property in the poyfill implementation I used.
> use CustomEvent to get IE11 working

- lib/cable_ready/channel.rb
- lib/cable_ready/channels.rb
@coderberry requested that CableReady operations be chainable. That was actually so easy, I'm a bit sad we didn't do this all along. I just had to modify `Channel#add_operation` to return `self`.
```ruby
cable_ready["MyChannel"].morph(selector: "body", content: "blah").dispatch_event(name: "boom", detail: {})
```
The logical progression from there was to be able to conclude a chain with `broadcast` or `broadcast_to`. This was a little more complicated, as the `Channel` class already had `broadcast` and `broadcast_to` methods. Arguably, this was unnecessarily confusing and disambiguating to `channel_broadcast` and `channel_broadcast_to` helps make the code easier to follow.
I changed the similarly confusing `Channel#add_operation` to `Channel#enqueue_operation` for similar reasons.
Anyhow, …
> method chaining

- javascript/cable_ready.js
All calls to `dispatch` would now test for the presence of jQuery, and if present, would initiate a matching jQuery event with the same name and details object.
> jquery support

- javascript/cable_ready.js
This partially undoes #71 by installing an additional guard. We don't want to trust `isEqualNode` comparisons for input/textarea/option elements for the reasons specified in #70.
> only compare isEqualNode for non-inputs

- lib/cable_ready/channel.rb
The current calling signature didn't match. This fixes that problem.
> Fix bug related to channel calling broadcast on the singleton

- javascript/cable_ready.js
- lib/cable_ready/channels.rb
```ruby
cable_ready[stream_name]
.storage_set_item(key: "local-example", value: "a value in local storage")
.storage_set_item(key: "session-example", value: "a value in session storage", type: "session")
.broadcast
cable_ready[stream_name]
.storage_remove_item(key: "local-example")
.storage_remove_item(key: "session-example", type: "session")
.broadcast
```
> Add support for sessionStorage and localStorage

- javascript/cable_ready.js
- lib/cable_ready/channels.rb
`set_storage` and `remove_storage` follow the naming convention used by every other operation.
I added a new optional `clear` flag to the `remove_storage` method that optionally clears all keys.
> changed storage method names, added clear flag

- javascript/cable_ready.js
Enhancement
Currently it just states `CableReady detected an error in morph! Object doesn't support this action` which makes it pretty hard to debug.
Now it's shown as an error (which it obviously is), shows the source where the error was thrown and prints the error separately so you can have a look the the error/stack-trace. 
Makes it easier to debug and DX.
> Add more detail to the CableReady error message

- lib/cable_ready/channels.rb
I suspect that this effectively undocumented feature (made real in #47) hasn't been working as intended for some time. I believe you can currently add operations with default behaviour. Unfortunately, custom behaviour just falls down in today's CableReady, especially where method chaining is concerned.
On the eve of real documentation emerging, I suspect people will want to make use of this feature, and this PR fixes it.
```rb
CableReady::Channels.configure do |config|
config.add_operation :jazz_hands do |options|
puts options.inspect
puts "Jazz hands!"
puts rand 1..1000
end
end
```
Now, I'm immediately putting this into draft because in truth... this might be a solution looking for a problem.
If this PR were accepted, the behaviour would be that the code in the block would execute when …
> rework custom operations

- javascript/cable_ready.js
- javascript/utils.js
**With genuine apologies for borking** #90.
This PR proposes the following changes:
1. All `selector` parameters now accept CSS queries that can return multiple elements. ~~Internally, `element` is now handled as an array. This includes the default, `[document]` and values returned via XPath.~~ `event.detail.element` is not an array unless `selectAll` is passed. Since nobody is currently using a feature that hasn't been released yet, this doesn't break SemVer.
2. There is a new `processList` utility function that handles calling operations either for the first element or all elements in the array, depending on whether the `selectAll: true` parameter has been passed. It defaults to just the first element, which should be the current behaviour.
3. I moved `activeElement = …
> multiple selector element operations

- javascript/cable_ready.js
Many operations will place the word `undefined` instead of an empty string if the critial parameter is omitted.
1. Nobody is looking for a way to emit `undefined`. This is not a feature.
2. There are many examples of operations where not specifying the critical parameter could be a feature if used creatively. For example, this PR would make it possible to:
```rb
cable_ready.inner_html(selector: "#foo")
```
This would erase the contents of the element.
Admittedly, I have already done this to the `set_value` operation before I realized that >50% of the operations would be better-suited to an empty string default.
> undefined no more

- javascript/cable_ready.js
- javascript/operations.js
It seems as though I was over-zealous in my enthusiasm for the `play_sound` operation; the bootstrap code interferes with strict CSPs and hijacks the audio context on a Mac.
This PR introduces a requirement that developers who wish to use the `play_sound` operation must place a `data-unlock-audio` attribute on their `body` tag. Otherwise, the operation will be a NOOP.
Fixes #111
> sound opt-in

- javascript/operations.js
- lib/cable_ready/config.rb
`set_meta` updates the `content` of a `meta` tag in the document head.
If no tag is found, it is created.
Here's a Nothing Reflex that updates a meta tag:
```rb
def meta
cable_ready.set_meta(name: "pill-messages", content: "5").broadcast
morph :nothing
end
```
I've found a really interesting pattern for building UI functionality that makes extensive use of `meta` tags.
```html
<span class="badge badge-md bg-danger text-white" data-controller="pill" data-pill-tag-value="messages">4</span>
```
This is all tied together with a Stimulus controller that observes `meta` tags:
```js
import { Controller } from 'stimulus'
export default class extends Controller {
static values = { tag: String }
initialize () {
this.metaTag = document.head.querySelector(
`meta[name=pill-${this.tagValue}]`
) …
```
> set_meta operation

- app/jobs/cable_ready_broadcast_job.rb
- lib/cable_ready/channel.rb
This PR enables to delegate broadcasts to a generic `CableReadyBroadccastJob` which is autoloaded from `app/jobs`.
Using `apply!` on the `operations_payload` this was a no-brainer, the only gotcha being that class stream identifiers of course cannot be serialized as such, so I had to do `identifier.name` on the sending and `identifier.safe_constantize` on the receiving side in case a `model` is present.
> broadcast_later

- .github/workflows/prettier-standard.yml
- bin/standardize
- javascript/cable_ready.js
- javascript/index.js
- javascript/morph_callbacks.js
- javascript/operation_store.js
- javascript/operations.js
- javascript/stream_from_element.js
- javascript/utils.js
- lib/cable_ready/config.rb
- package.json
Feature
This PR introduces a `OperationStore` to add operations on-the-fly.
This also removes the `playSound` operation. The operation has been extracted to: https://github.com/cableready/audio_operations
With that a developer can add custom operations from packages to their app.
```javascript
// app/javascript/packs/application.js
import CableReady from 'cable_ready'
import AudioOperations from '@cable_ready/audio_operations'
CableReady.addOperations(AudioOperations)
```
As CableReady is more than just "DOM operations" we should also change the name. This is still supported but shows a deprecation warning:
```javascript
CableReady.DOMOperations.jazzHands = (operation, name) => {
console.log('Jazz hands!', operation)
}
```
Instead you can now use this:
```javascript …
```
> Introduce `OperationStore` to add operations on-the-fly

- javascript/operations.js
- lib/cable_ready/config.rb
Implements https://developer.mozilla.org/en-US/docs/Web/API/Console/table as an operation.
Options:
- data
- columns
Anything passed to data is sent into the table. It expects an array or object, but fails very gracefully.
Columns defaults to `[]` and must be an array of strings if passed.
```rb
cable_ready.console_table(data: [{marco: 5, nate: 2}, {marco:4, nate: 6}], columns: ['marco']).broadcast
```
Thanks to @MatheusRich for the idea!
> console_table operation

- javascript/stream_from_element.js
"Bug fix"
In #124 I introduced a warning message that would warn a developer if the custom element `stream-from` was already registered. It turns out that we can't check it that easily with our setup - especially if you are using CableReady via a different package in your app. 
Long story short: This PR removes that check since it always showed the warning message, even if everything was fine.
To avoid confusion about the already registered custom element.
> Remove warning message for already registered custom element

- lib/cable_ready/identifiable.rb
- lib/cable_ready/operation_builder.rb
- test/lib/cable_ready/cable_car_test.rb
- test/lib/cable_ready/identifiable_test.rb
Resolves #134 
FYI, I added `to_s` onto the final path for the updated selector logic, but that might be a breaking change (since previously a non-String object would be converted via `to_json`, not `to_s`). There's also the outstanding question of whether we need to issue a warning or exception if something mangled gets through like an inspect string with class name, etc.
Happy to work on updated docs as well, just let me know.
> Support `to_dom_selector` for operation selectors

- lib/cable_ready/identifiable.rb
I'm pretty sure that the output of the `dom_id` method should always be lower-cased. Right now, if you pass a constantized value like `User` it'll return `#User`. I don't think that's a thing... it might not be a rule, but it's certainly a convention.
Thoughts?
> dom_id should always be lowercase

- package.json
Second verse, same as the first. Just like SR.
> chore: make webpack happy with no sideEffects

- lib/cable_ready.rb
Based on conversations I was having with @leastbad yesterday, it sounds like establishing a dedicated MIME type for CableReady JSON responses delivered via cable_car could have a lot of benefits.  This PR registers the `application/vnd.cable-ready.json` MIME type as a `cable_ready` format within rails.
Generally speaking, it facilitates architecture patterns I've seen @hopsoft advocating of using one controller to deliver multiple formats.  A dedicated content type will allow the same controller action to serve both cable_ready or traditional JSON API requests:
```ruby
respond_to do |format|
format.cable_ready { render operations: cable_car ... }
format.json
```
More specifically, registering this content type within the cable_ready gem will facilitate some changes I'm proposing to the …
> register a CableReady JSON MIME type

- lib/cable_ready/operation_builder.rb
- test/lib/cable_ready/operation_builder_test.rb
This was inspired by conversations with @rrosen and @jaredcwhite. Rafe talked about how when he came to Ruby, he was inspired by the idea that objects should "just know what to do". And Jared's recent #135 was - at its core - about making it possible for an object to take responsibility for its DOM selector. This PR is hopefully the natural conclusion of both thoughts.
Allows objects that conform to the `to_xxx` naming convention optionally provide a value to matching options.
```rb
class Death
def to_html
"I rock"
end
end
```
```rb
death = Death.new
cable_car.inner_html(html: death) # => "innerHtml" => [{"html" => "I rock"}]
```
```rb
class Death
def to_html
"I rock"
end
def to_dom_id
"death"
end
end
```
```rb
death = Death.new
cable_car.inner_html(death, html: death) # => "innerHtml" => …
```
> Smart options (they grow up so fast)

- javascript/operations.js
- lib/cable_ready/config.rb
Will test for `window.Turbo` and `window.Turbolinks` before falling back on `window.location.href`
[`action` option](https://github.com/turbolinks/turbolinks#turbolinksvisit) is supported, defaults to `advance`
> redirect_to operation

- javascript/stream_from_element.js
Fix this error:
```sh
ERROR in ./.yarn/cache/cable_ready-npm-5.0.0-pre3-b6a471a50a-bf6c2acdbd.zip/node_modules/cable_ready/javascript/stream_from_element.js 15:33-51
export 'default' (imported as 'CableReady') was not found in 'cable_ready' (possible exports: initialize, perform, performAsync)
```
> Fix wrong CableReady import

- javascript/updates_for_element.js
- javascript/utils.js
- package.json
- removed sideEffects from package.json
- renamed Boris function to debouncer
- refactored updates_for to support different URLs
- adds and removes `updating` attribute for CSS
Outstanding points and questions:
- I'm a little fuzzy on how we should be handling `assignFocus` with multiple blocks being updated
- right now, debounce is set by the first web component; specifying a different value on a later `updates_for` will have no effect
- currently, the `updating` attribute is added and removed to and from each element in a cascade; if you want all elements to receive and lose their `updating` attribute at the same time, I will have to rework this slightly
- I'm not 100% sure what happens if there aren't enough blocks on a page referenced by `url`, this might require a try/catch
"Test" …
> post-pre4 updates

- javascript/elements/updates_for_element.js
- javascript/utils.js
Allows to fetch and patch lazy loaded turbo frames present in the response eagerly.
> Query all eager loading turbo frames and patch their innerHTML

- javascript/index.js
the error is:
Should not import the named export 'version' (imported as 'version') from
default-exporting module (only default export is available soon)
> fix: resolve error for webpack 5

- Gemfile.lock
- cable_ready.gemspec
Most apps don't require the full suite of Rails gems, and can avoid installing them to save CI and deploy time. This gem, however, had a dependency on the Rails meta-gem which ended up installing them all anyways.
Instead, we can limit it to only the Rails gems that we directly depend upon.
I'm not sure how to really test this, since the dummy app uses all of Rails. I grep'd through `./lib` to see what parts of Rails were being used, but that might not be comprehensive.
_Note_: I ran `./bin/standardize` as instructed by the README, but it touched dozens of files which I didn't commit as part of this PR.
> Updated gemspec to specific Rails gems

- app/models/concerns/cable_ready/updatable.rb
- app/models/concerns/cable_ready/updatable/model_updatable_callbacks.rb
This adds a `skip_updates` option to wrap any database CRUD changes in that should not be broadcast, for example because they are [happening in an environment without a running Redis server](https://github.com/stimulusreflex/cable_ready/issues/167).
```ruby
class ApplicationRecord < ActiveRecord::Base
include CableReady::Updatable
self.abstract_class = true
end
ApplicationRecord.skip_updates do
User.destroy_all
User.create!(user_attrs)
end
User.skip_updates do
User.destroy_all
User.create!(user_attrs)
Post.destroy_all
Post.create!(post_attrs)
end
```
Big thanks to @leastbad and @julianrubisch for pointing me in the right direction 🤗 I decided to borrow heavily from ActiveRecord's [no_touching](https://github.com/rails/rails/blob/83217025a171593547d1268651b446d3533e2019/activerecord/lib/act …
> Add `skip_updates` option

- app/helpers/cable_ready_helper.rb
- javascript/cable_ready.js
- javascript/elements/updates_for_element.js
- javascript/updatable/inner_updates_compat.js
Let me preface this PR with the fact that this is already being used successfully in production and is intended as a backmerge of the work I'm doing at https://github.com/code-and-co/.
The idea is to opt out of an `updates_for` operation for the current user on a per-element basis, when a reflex or turbo submit is happening (for example, when wrapping a `<turbo-frame>`).
Conceptually, it consists of 3 parts:
which recursively marks every enclosing `updates-for` element with `performing-inner-update`, starting from a reflex or turbo submit initiating element. This attribute is removed again after completion.
which adds a `ignore-inner-update` attribute to the element on demand.
combining the existing "only" option and returning early when both `ignore-inner-updates` and …
> Ignore inner updates on a stimulus-reflex action or turbo submit

- javascript/operations.js
Bug Fix
This PR adds a check to make sure that we use the provided `text` parameter if it's not nullish
The `text_content` operation always used an empty string for the `text` parameter if the value of the `text` parameter was nullish.
Previously if you passed in `0` as a value for `text` it would have still used the empty string instead.
> Fix `text_content` operation for nullish values

- .github/workflows/dev-build.yml
CI
This sets up automated dev-builds for all commits and pull requests in order to make the development easier with pre-released code. With #165 we added a build-step to our npm package which might break if you are installing the npm package from a GitHub branch.
Using the first eight characters of the commit hash you can install and use the desired CableReady dev-build in your application.
You can install a dev-build using the `yarn add` command like:
```bash
yarn add cable_ready@https://github.com/cableready/dev-builds/archive/cable_ready/fa083b0.tar.gz
```
or directly replace the `cable_ready` dependency in your `package.json`:
```json5
// package.json
{
// ...
"cable_ready": "https://github.com/cableready/dev-builds/archive/cable_ready/fa083b0.tar.gz"
}
```
Makes it super easy and …
> Setup automated dev-builds

- javascript/elements/updates_for_element.js
This PR used to be #182.
Reworked updates-for element to allow per-block url and only attributes. URL fragment indexes are now tracked on a per-URL basis.
That means the following contrived example works as you'd expect:
`index.html.erb`
```erb
<%= updates_for current_user, :posts do %>
<% Post.all.each do |p| %>
<p><%= p.name %>, <%= p.email %></p>
<% end %>
<p><%= rand(1..1000) %></p>
<% end %>
<%= updates_for current_user, :posts, only: [:name] do %>
<% Post.all.each do |p| %>
<p><%= p.name %>, <%= p.email %></p>
<% end %>
<p><%= rand(1..1000) %></p>
<% end %>
<%= updates_for current_user, :posts, url: "/updates_for" do %>
<% Post.all.each do |p| %>
<p><%= p.name %>, <%= p.email %></p>
<% end %>
<p><%= rand(1..1000) %></p>
<% end %>
<%= updates_for current_user, :posts, only: [:name], …
```
> updates-for should respect url and only params on each element

- javascript/elements/updates_for_element.js
Mainly this pulls together everything that reaches out to `block` in its own class, and, more importantly, does a pre-pass of fetching unique URLs
While this is an improvement in general and might fix some of the multi-fetches occurring, I still saw some instances where the same URL was fetched twice, ~even from the same elements~.
What I can say though is that in the app I'm testing it against, we have a fair amount of `touch`es happening in the class hierarchy, so I think what we're _really_ looking at is another opportunity to look at **server side debouncing**
cc @andrewerlanger
> Extract Block class and do a pre-fetch pass

- cable_ready.gemspec
Improvement
CableReady is going to get it's own installers soon (see #179). In order for the rake files to be inculded we need to add the `.rake` extension to the gemspec. This PR is analog to https://github.com/stimulusreflex/stimulus_reflex/pull/581.
> Add `.rake` to gemspec `files` glob pattern

- app/helpers/cable_ready_helper.rb
- test/lib/cable_ready/helper_test.rb
In the app I'm currently developing, it has occurred that I want to conditionally wrap a block of ERB in `updates_for` based on authorization. So typically one would do:
```erb
<% if policy(post).edit? %>
<%= updates_for post ... %>
<%= post.content %>
<% end %>
<% else %>
<%= post.content %>
<% end %>
```
which, depending on your setup, might lead to a lot of duplication. This PR simplifies it to
```erb
<%= updates_for_if policy(post).edit?, post ... %>
<%= post.content %>
<% end %>
```
in the spirit of `link_to_if` etc.
> Add conditional updates_for helper

- javascript/cable_ready.js
- javascript/utils.js
Acting on a request from @W3NDO, this PR would allow the `select_all` option to co-exist with `xpath` selectors.
It required the introduction of a `xpathToElementArray` utility function, which returns an Array of nodes (that could be empty, depending on your query results).
> multi-element XPath support

- javascript/operations.js
Enhancement
@mepatterson asked on Discord if it's possible to use the `redirectTo` operation without using Turbo and Turbolinks even though it's actually installed and setup in the app. There are some edge-cases were you might want to not use the `visit()` function.
This Pull Requests adds an option to disable the navigation with Turbo/Turbolinks in the `redirectTo` operation, since there is no simple way to disable the use of the `Turbo[links].visit()`.
You could also solve this issue with a simple custom operation like:
```js
CableReady.operations.navigate = (operation) => {
window.location.href = operation.url
}
```
But it somehow seems redundant since there's already an operation which pretty handles this out of the box, if configured properly.
> Add option to disable Turbo Drive/Turbolinks on `redirectTo` navigation

- javascript/updatable/inner_updates_compat.js
In certain scenarios, the call to recursive updates associated with updates_for may fail if the leaf's parent Element is null.  
This results in an error similar to the following:
`Uncaught TypeError: e2.parentElement is null`
To prevent the error we'll perform an explicit check on the presence of the parent element before attempting to call closest().
> Explicit check for leaf parent element presence for updates_for

- javascript/operations.js
- lib/cable_ready/config.rb
This adds an operation which allows you to call a JavaScript method for an element, whether that's a builtin HTML element or a custom element. Or you can use `window` as the receiver instead of an element. Example:
```ruby
cable_car.invoke_method "#some-element", method: :doSomething,
args: ["wow", { very: "cool" }], # you can (optionally) pass any number of args via an array
delay: 1000 # as with all operations now, you can delay it by X ms
cable_car.invoke_method receiver: :window, method: "Turbo.visit", args: ["/path"]
```
> Add an `invoke_method` operation

- lib/cable_ready/operation_builder.rb
- test/lib/cable_ready/operation_builder_test.rb
Bug Fix
The `OperationBuilder#apply!` method somehow didn't account for passing an Array into it when trying to apply operations to a channel. Instead it added the array of operations to the `@enqueued_operations` ending up in a nested array.
The nested `@enqueued_operations` resulted in a `NoMethodError (undefined method 'deep_transform_keys!' for []:Array):` when trying to use in combination with the `.broadcast_later` method. This PR fixes the `apply!` method to also take an array of operations.
```ruby
irb(main):002:0> cable_ready["example"].broadcast_later
Enqueued CableReadyBroadcastJob (Job ID: f7e8dd9b-8072-406c-8228-1d7cc36307ec) to Async(default) with arguments: {:identifier=>"example", :operations=>[]}
=> nil
Performing CableReadyBroadcastJob (Job ID: …
```
> `OperationBuilder#apply!` should be able to handle an array of operations

- javascript/operations.js
- javascript/utils.js
I applied @marcoroth's `value != null ? value : ''` to the CR operations which previously would have read `value || ''`. The issue was that if the developer sends `0` as a value, in JS `0` is falsey and so the OR falls over to `''`.
Some applications are more straightforward than others. Anything where a text/html value was being written, this is an obvious fix. However, in an attempt to be thorough, I also updated a few that I would appreciate 👀 on:
- `addCssClass`: can you have a class with the name `0`? I sort of doubt it.
- `pushState` and `replaceState`: should I be applying this to the `state` param? (I have it falling back to `{}`)
- `setCookie`: is this appropriate?
- `consoleTable`: is this appropriate?
> fixed 0 value problem with null checks

- javascript/operations.js
- javascript/utils.js
In the process of testing https://github.com/stimulusreflex/stimulus_reflex/pull/601, I realized that three operations attempt to access the `parentElement`. This doesn't work out if you are targeting `html`.
Snuck in a tiny util function, `fragmentToString`. I intend to use it for tests and etc.
> documentElement doesn't have a parent

- javascript/cable_ready.js
- javascript/elements/index.js
- javascript/elements/stream_from_element.js
- javascript/missing_element.js
Here's a pass at customizable missing element warnings. I'm not attached to my approach; feel free to suggest different variable names, different attribute names, changes to the behaviour of the different modes.
I should also say that it occurred to me only as I was typing this up that perhaps this is actually the wrong approach; instead of specifically addressing missing elements, perhaps it would be better to implement a `debug` concept that would allow the developer to make decisions for all errors. There are lots of warnings etc in the codebase that have nothing to do with missing elements. **Opinions, please!**
After deliberation, I took Marco's idea to have multiple strategies and ran with it. I figure that we can always pull these extra options out if we don't want them. …
> missing element warnings

- .github/workflows/standardrb.yml
Enhancement
Updates the StandardRB GitHub Action to run on a more recent Ruby version and removes the now deprecated [`CultureHQ/actions-bundler`](https://github.com/CultureHQ/actions-bundler) action.
Removes one "dependency", makes the action faster and should resolve the issues around standardrb in #222.
> Modernize StandardRB GitHub Action

- app/helpers/cable_ready/view_helper.rb
- lib/cable_ready_helper.rb
- test/lib/cable_ready/view_helper_test.rb
Recently @marcoroth namespaced the helper file under the CableReady namespace (#220). This broke using `stream_from` view helper since Rails seems to prefer a helper be called xxxHelper. I've made a suggestion to rename Helper to ViewHelper. I'm very open to other names though.
This makes the `stream_from`, `updates_for` and other view helpers work again.
> Rename Helper to ViewHelper so Rails will include it correctly

- javascript/elements/updates_for_element.js
Bug fix
Modify `updates_for` element to verify that a page is required before fetching it.
This PR essentially implements the suggestion made in #209, with minor tweaks.
I've done my best to test this new functionality, but I am not a heavy user of `updates_for` and would appreciate if @julianrubisch could sanity check this. Specifically, my concern is that there could be an unexpected interaction with lazily loaded Turbo Frame content?
I was concerned that filtering out blocks might cause the index-based element selection to point to the wrong element, but so far, I haven't been able to trip it up. I really don't want to break this functionality.
@andrewerlanger I also removed the previous line 117, which was where we performed the `shouldUpdate` check initially. It seems as though this …
> fix `updates_for` makes redundant calls

- javascript/operations.js
- lib/cable_ready/config.rb
Feature
`cable_ready.set_title(title: "Introducing...")`
@drnic needs a `set_title` operation, so he gets one.
> set_title operation

- javascript/utils.js
Enhancement
StimulusReflex and CableReady shared the same `xpathToElementArray`,`debounce` and a similar `dispatch` util function. 
In order so resolve https://github.com/stimulusreflex/stimulus_reflex/issues/571 we now sync the changes to CableReady so that we can remove the util functions form StimulusReflex. 
Less code and code sharing is always good.
> Sync utils from StimulusReflex

- javascript/operations.js
- lib/cable_ready/config.rb
Extraction
The `invoke_method` operation has been extracted to https://github.com/cableready/invoke_operations
> Extract `invoke_method` operation

- javascript/updatable/inner_updates_compat.js
This PR adds the TB-Commands events to the `inner-updates-compat` module, because otherwise mutating a model could result in multiple Updates firing the Turbo Boost Commands controller action again.
> chore: Make Updatable aware of Turbo Boost Commands

- lib/cable_ready/config.rb
- lib/cable_ready/engine.rb
- lib/generators/cable_ready/templates/config/initializers/cable_ready.rb
Like ActionCable: https://github.com/rails/rails/blob/main/actioncable/lib/action_cable/engine.rb#L27 
Useful when using Webpacker to manage static assets
> Add setting switch to disable assets compilation

- javascript/debug.js
- javascript/elements/updates_for_element.js
- javascript/index.js
- javascript/updatable/log.js
Ports over some client side logging functionality from StimulusReflex to better be able to debug and benchmark `Updatable`  interactions.
As in StimulusReflex, logging has to be explicitly enabled by passing `{debug: true}` to `CableReady.initialize`.
Fixes #246
> Updatable logging

- app/models/concerns/cable_ready/updatable.rb
- test/dummy/app/models/dugong.rb
- test/dummy/app/models/section.rb
- test/dummy/app/models/supplier.rb
- test/dummy/app/models/team.rb
- test/dummy/app/models/topic.rb
- test/dummy/app/models/user.rb
- test/lib/cable_ready/updatable_test.rb
Enforcement of Consistency 
This pull request renames the two class methods and relation options related to the `CableReady::Updatable` module:
* option `enable_updates` to `enable_cable_ready_updates`
* class method `enable_updates` to `enable_cable_ready_updates`
* class method `skip_updates` to `skip_cable_ready_updates`
The class methods were super generic and didn't indicate that they were originating from CableReady. The method names were also more likely to clash with other upcoming gems which would port this behavior to a Turbo-related project.
All of the deprecated methods and the options emit a warning if they are used so people know how to migrate them. 
```diff
class Post < ApplicationRecord
include CableReady::Updatable
- has_many :users, enable_updates: true
+ has_many …
```
> Rename `enable_updates` to `enable_cable_ready_updates`

- test/lib/cable_ready/config_test.rb
Tests
Adds test coverage for the `CableReady::Config` class
Increasing the test coverage is always good.
> Add tests for `CableReady::Config`

- app/helpers/cable_ready/view_helper.rb
- test/lib/cable_ready/view_helper_test.rb
Fixes the broken `dom_id` helper that was cause by `ViewHelper` including `Broadcaster`, which in turn included `Identifiable`, which contains a patched version of dom_id
> fix: dom_id from view helper

- app/helpers/cable_ready/view_helper.rb
- javascript/elements/stream_from_element.js
- javascript/elements/subscribing_element.js
- javascript/elements/updates_for_element.js
- test/lib/cable_ready/view_helper_test.rb
Consistency Enforcement
Similarly to #250 this pull requests scopes the custom HTML elements and view helpers with the `cable_ready` name.
* `<stream-from>` -> `<cable-ready-stream-from>`
* `<updates-for>` -> `<cable-ready-updates-for>`
There's nothing to migrate here, since those element names were just used under the hood.
* `stream_from` -> `cable_ready_stream_from`
```diff
-<%= stream_from Photo %>
+<%= cable_ready_stream_from Photo %>
```
* `updates_for` -> `cable_ready_updates_for`
```diff
-<%= updates_for @feed, :comments do %>
+<%= cable_ready_updates_for @feed, :comments do %>
<%= render @feed.comments %>
<% end %>
```
* `updates_for_if` -> `cable_ready_updates_for_if`
```diff
-<%= updates_for_if @feed.updates?, @feed, :comments do %>
+<%= cable_ready_updates_for_if …
```
> Scope CableReady custom HTML elements and view helpers

- lib/cable_ready.rb
- lib/cable_ready_helper.rb
- test/lib/cable_ready/view_helper_test.rb
Enhancement
Instead of raising an exception when including the `CableReadyHelper` module we print a warning and include the right `CableReady::ViewHelper` module anyway, so we are not breaking any existing code.
This is a much better DX than raising an error and requiring the developer to fix it right away.
> Don't raise when including `CableReadyHelper`

- docs/guide/action-cable.md
ActionCable guide page had old reference to StimulusReflect authentication guide
Fixes invalid link
> Fix link to StimulusReflex authentication guide

- app/jobs/cable_ready/broadcast_job.rb
- lib/cable_ready/channel.rb
Puts the `BroadcastJob` in the `CableReady` namespace.
To line it up with all the other modules.
> Namespace Broadcastjob

- app/models/concerns/cable_ready/updatable.rb
- test/dummy/app/models/site.rb
- test/dummy/db/migrate/20230301080311_create_sites.rb
- test/dummy/db/schema.rb
- test/dummy/test/fixtures/sites.yml
- test/dummy/test/models/site_test.rb
- test/lib/cable_ready/updatable_test.rb
One of the big downsides of using `CableReady::Updatable` in the wild is that it can lead to a lot of noise on the ActionCable connection. This is because every change on a model that enables updates leads to a ping being sent over ActionCable due to the usage of ActiveRecord callbacks.
This PR introduces a `debounce:` option that takes an `ActiveSupport::Duration` argument that will only send out one ping for this model per debounce period.
It makes use of a simple internal per-process `MemoryDebounceAdapter`, which is just a thin synchronized layer around a `Hash`.
Preparations are made, however, to override this adapter using a `CableReady::Updatable.debounce_adapter` mattr_accessor, which can be overridden in an initializer. This should make it possible to devise other adapters (for …
> Debounced updatable

- app/models/concerns/cable_ready/updatable.rb
- app/models/concerns/cable_ready/updatable/collections_registry.rb
- package.json
- test/dummy/app/models/listing.rb
- test/dummy/app/models/listings.rb
- test/dummy/app/models/listings/action.rb
- test/dummy/app/models/user.rb
- test/dummy/db/migrate/20230301110606_create_listings.rb
- test/dummy/db/migrate/20230301112847_create_listings_actions.rb
- test/dummy/db/schema.rb
- test/lib/cable_ready/updatable_test.rb
This is more or less a reimplementation of a patch that @andrewculver made to fix `inverse_of` resolution. I just took it a bit further and lazy loaded/stored reflection properties in the finder, because it's useless to do the work twice, and declutters the main module a bit
https://github.com/stimulusreflex/cable_ready/compare/master...andrewculver:cable_ready:master?diff=split
(maybe) Fixes #258 
awaiting confirmation from the BulletTrain team cc @andrewculver
> Fix inverse of resolution

- app/models/concerns/cable_ready/updatable.rb
- lib/cable_ready/config.rb
- lib/generators/cable_ready/templates/config/initializers/cable_ready.rb
- test/lib/cable_ready/config_test.rb
- test/test_helper.rb
Allows to set the default `updatable_debounce_time` in the CableReady config. This allows every application to set it to a desired value
> Set default debounce time in CableReady::Config

- app/models/concerns/cable_ready/updatable.rb
- lib/cable_ready.rb
- lib/cable_ready/updatable/memory_cache_debounce_adapter.rb
Makes the memory debounce adapter use `ActiveSupport::MemoryCacheStore` inherently, with a default expiration time of 5 minutes.
Note that I also moved it to a new adapters directory in anticipation of other adapters.
> Make memory debounce adapter use MemoryCacheStore

- app/models/concerns/cable_ready/updatable.rb
- app/models/concerns/cable_ready/updatable/collections_registry.rb
- app/models/concerns/cable_ready/updatable/model_updatable_callbacks.rb
- test/dummy/app/models/rule.rb
- test/dummy/app/models/site.rb
- test/dummy/db/migrate/20230303125513_create_rules.rb
- test/dummy/db/schema.rb
- test/lib/cable_ready/updatable_test.rb
This is an extension of the debounce mechanism to associations. Note that I switched to passing the debounce time around via method arguments rather than instance variables, because it was cleaner to do so from both the model class as well the association extension side.
There may be some opportunities to declutter this a bit, though at the moment they're not obvious to me.
> Updatable debounce associations

- lib/tasks/cable_ready/cable_ready.rake
Bug fix
The CableReady installer still had an include for `include Rails.application.routes.url_helpers`, which is not used anymore. This pull request removes that include call.
Fixes #265 
Since we don't need to have all route url helpers in the global namespace we can remove the call. Additionally, it also causes some issue in certain cases, see #265.
> Remove unused `url_helpers` include from installer

- docs/guide/cable-car.md
- docs/guide/cableready-everywhere.md
- lib/cable_ready/engine.rb
Deprecation + Enhancement
CableReady's `render operations:` ActionController renderer doesn't indicate that it's coming/being used for CableReady operations. This pull request renames the renderer to `render cable_ready:` and adds a deprecation warning for the `operations` renderer.
Additionally it make the DX around it a little bit better by checking if the passed argument responds to `.dispatch` before calling it. This helps when you already called `.dispatch` in the controller action or if you provide it a already converted JSON string.
This pull request also changes the `cable_ready` MIME type from `application/vnd.cable-ready.json` to `text/vnd.cable-ready.json` so that the response from a controller action can be viewed in a browser.
Finally, this pull request adds the …
> Rework CableReady's `ActionController::Renderers`

- javascript/elements/updates_for_element.js
I think we have a misnamed variable hidden lurking about in `updates_for_element.js`. Specifically: a `docFragment` that should read `documentFragment` (leading to `ReferenceError: docFragment is not defined`).
This PR updates the name accordingly.
> Fix ReferenceError

- cable_ready.gemspec
Bug fix
All template files for the installer (`*.js.tt`) were missing in the bundled gem. This pull requests adds the `*.tt` ending to the `files` config inside the `gemspec`.
So the installer works properly again. The installer was failing with:
```ruby
--- [esbuild] ----
rails aborted!
Thor::Error: Could not find "/3.2.0/gems/cable_ready-5.0.0.rc2/lib/generators/cable_ready/templates/esbuild.config.mjs.tt" in any of your source paths. Your current source paths are:
/3.2.0/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/generators/rails/app/templates
Tasks: TOP => app:template
(See full trace by running task with --trace)
--- [config] ----
rails aborted!
Thor::Error: Could not find "/3.2.0/gems/cable_ready-5.0.0.rc2/lib/generators/cable_ready/templates/app/javascript/config/index.js.t …
```
> Include `*.js.tt` files in bundled gem

- app/models/concerns/cable_ready/updatable.rb
- lib/cable_ready/config.rb
- lib/cable_ready/engine.rb
This allows to set a different debounce adapter than the built-in one, in preparation to building one with https://github.com/hopsoft/composite_cache_store/
Initially I wanted to move the `MemoryCacheDebounceAdapter` to `lib/cable_ready/updatable/memory_cache_debounce_adapter.rb`, but that again resulted in weird Zeitwerk issues when requiring it that led nowhere. That's why I opted into defining the default adapter in a config hook.
Eventually we'll want to move the whole updatable cod from `app/` to `lib/`.
> Debounce adapter config option

- javascript/elements/updates_for_element.js
- javascript/updatable/log.js
- javascript/utils.js
Furnishes cable-ready-updates-for-element with instance variables for element logs, so they can displayed in the devtools like this:
> Add trigger and target element logs for devtools

- docs/guide/updatable.md
- javascript/elements/updates_for_element.js
Added documentation about failing updates, and output the offending element in the browser console.
> Updatable doc updates

- lib/cable_ready/operation_builder.rb
- test/lib/cable_ready/operation_builder_test.rb
When chaining operations that use a `selector` argument, subsequent operations can optionally omit the `selector` argument and the `selector` from the previous operation gets applied applied automatically (at line 46 of `CableReady::OperationBuilder` [here](https://github.com/stimulusreflex/cable_ready/blob/main/lib/cable_ready/operation_builder.rb#L46).
There's a weird edge case here that can cause the subsequent operation to fail if the first operation was using `xpath`, because the `selector` argument gets set but the `xpath` argument does not get set and defaults to `false`, eg:
```ruby
cable_ready
.add_css_class(name: "example", selector: "/html/body/div[1]", xpath: true) # succeeds
.inner_html(html: "fail") # fails
```
The first operation is applied correctly but the `inner_html` …
> Set xpath flag if/when overwriting selector with previous_selector

- lib/cable_ready/channels.rb
- lib/cable_ready/config.rb
Enhancement
When using the CableReady gem (or the `cable_ready-element` gem to be specific) outside of a Rails context it was complaining about undefined methods for:
```
NoMethodError: undefined method `seconds' for 0.1:Float
rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cable_ready-5.0.1/lib/cable_ready/config.rb:31:in `initialize'
```
and
```
NoMethodError: undefined method `many?' for [{:message=>"Test"}]:Array
rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cable_ready-5.0.1/lib/cable_ready/operation_builder.rb:41:in `block in add_operation_method'
```
Requiring the right ActiveSupport core extensions resolves those errors.
This makes the gem more portable and less Rails-dependent.
> Require needed ActiveSupport core extensions

- app/helpers/cable_ready/view_helper.rb
- javascript/elements/updates_for_element.js
- javascript/observers/appearance_observer.js
This PR addresses an optimization regarding the number of requests that `Updatable` possibly makes.
The rationale is this: it doesn't really make sense to keep elements that aren't visible up to date. this can be deferred, which defaults to lazy loading.
We have to distinguish 3 cases here:
- is visible - behavior as usual
- is not visible - ignore requests. Basically shouldUpdate == false
- transition from invisible to visible - pull and morph once, then listen as normal
I leaned on Turbo's solution here a bit, and introduced a separate `AppearanceObserver`. The thing I added to the regular `IntersectionObserver` is an observer for `document.visibilityState`. This means:
- not only hidden elements in the DOM tree of the opened browser tab
- but also generally elements that are in browser …
> Wrap updates-for-element in an IntersectionObserver

- Gemfile.lock
- cable_ready.gemspec
Enhancement
Ruby 3.4 removes the `observer` gem from the standard gems which is why we have the declare the dependency explicitly now.
From https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/:
> ### Standard library updates
> RubyGems and Bundler warn if users do require the following gems without adding them to Gemfile or gemspec. This is because they will become the bundled gems in the future version of Ruby.
Fixes #293 
To provide Ruby 3.4+ support.
> Add `observer` gem to gemspec

- lib/cable_ready/installer.rb
- lib/install/action_cable.rb
- lib/install/broadcaster.rb
- lib/install/bundle.rb
- lib/install/compression.rb
- lib/install/config.rb
- lib/install/development.rb
- lib/install/esbuild.rb
- lib/install/importmap.rb
- lib/install/initializers.rb
- lib/install/mrujs.rb
- lib/install/npm_packages.rb
- lib/install/shakapacker.rb
- lib/install/spring.rb
- lib/install/updatable.rb
- lib/install/vite.rb
- lib/install/webpacker.rb
- lib/install/yarn.rb
Enhancement
This pull request isolates the methods defined `lib/cable_ready/installer.rb` into a `CableReady::Installer` constant so they don't pollute the global namespace if the file is required.
Exposing all the methods from the installer in the global namespace could lead to issues down the road. Methods like `options` are likely to be overridden.
> Isolate and namespace `CableReady::Installer`

- javascript/elements/updates_for_element.js
Bug fix
Unsubscribe from the channel by calling superclass's (SubscribingElement) disconnectedCallback.
Fix repeated subscribe messages after a morph.
> Unsubscribe from the channel when UpdatesForElement disconnects

- app/models/concerns/cable_ready/updatable/collections_registry.rb
Handle resolving a dangling (`optional: true`) belongs_to inverse association gracefully
> Apply safe navigation when resolving optional belongs_to resource
